package com.example.analizadorlexico;

enum TipoToken {
    PALABRA_RESERVADA,
    IDENTIFICADOR,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    OPERADOR_ARITMETICO,
    INCREMENTO,
    DECREMENTO,
    ASIGNACION,
    NUMERO_ENTERO,
    NUMERO_DECIMAL,
    CADENA_CARACTERES,
    COMENTARIO,
    COMENTARIO_LINEA,
    PARENTESIS,
    LLAVE,
    ERROR
}
